version: '3'
services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
