version: '3'
services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/usr/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
